//当引用了不存在的变量时，抛出的错误类型为（）。ReferenceError
//当调用了不存在的方法时，抛出的错误类型为（）。TypeError


try{
    可能出现错误的代码
}eatch( e ){
    处理错误的代码(如果出现错误就执行)
}
...
、、、
1，代码正常运行，如果在try 中出现了错误，try里面出现错误的语句后面的代码都不执行，直接跳转到catch
2，catch中处理错误信息
3，然后继续执行后面的代码
4，如果try中没有出现错误，那么不走 catch  直接执行后面的代码

## 如何抛出异常

、、、
throw对象
、、、

1，throw 是抛出异常的语法，其后跟一个对象，即错误消息对象
2，一般该对象使用^new Error('错误消息')^来创建，也支持任意的对象

、、、
function showMessage(msg){
    //要显示一段文本，所以我做一个限制
    if( typeof msg !== 'string' ){
        throw new Error( '传入的参数不是一个字符串' )
    }
    //是正常的
    console.log(msg);
}
、、、

